version: "3"

services:
    Router:
        image: handsonsecurity/seed-ubuntu:large
        container_name: router
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.11
            net-10.8.0.0:
                ipv4_address: 10.8.0.11
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.8.0.1 &&
                      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
                      tail -f /dev/null "

    user:
        build: ./images/host_a
        image: seed-user
        container_name: Host-A
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.7
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.9.0.11 &&
                      /start.sh "

    local-server:
        build: ./images/local_dns_server
        image: seed-local-dns-server
        container_name: local-dns-server-10.9.0.71
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.71
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.9.0.11 &&
                      service named start && tail -f /dev/null "
                  
    

    attacker:
        image: handsonsecurity/seed-ubuntu:large
        container_name: malicious-user
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        network_mode: host

    attacker-ns:
        build: ./images/malicious_ns
        image: seed-attacker-ns
        container_name: malicious-ns-10.9.0.171
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.171

networks:
    net-10.8.0.0:
        name: net-10.8.0.0
        ipam:
            config:
                - subnet: 10.8.0.0/24

    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24


